// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const host = env("DB_HOST");
const port = env("DB_PORT");
const user = env("DB_USER");
const pass = env("DB_PASSWORD");
const db = env("DB_NAME");

export default defineConfig({
  schema: "src/database/prisma/schema.prisma",
  migrations: {
    path: "src/database/prisma/migrations",
    seed: "tsx src/database/prisma/seed.ts",
  },
  datasource: {
    url: `mysql://${user}:${pass}@${host}:${port}/${db}`,
  },
});
